[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SUNRepresentations = "1a50b95c-7aac-476d-a9ce-2bfc675fc617"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"

[compat]
Documenter = "1"
DocumenterInterLinks = "1"
LinearAlgebra = "1"
Random = "1"
SUNRepresentations = "0.3"
Test = "1"
WignerSymbols = "1,2"
